su-per-no-va/fashion-nova

build.gradle, src/main/java/com/supernova/fashionnova/global/config/WebSecurityConfig.java, src/main/java/com/supernova/fashionnova/global/exception/ErrorType.java, src/main/java/com/supernova/fashionnova/global/util/ResponseUtil.java, src/main/java/com/supernova/fashionnova/security/JwtAuthenticationFilter.java, src/main/java/com/supernova/fashionnova/security/JwtAuthorizationFilter.java, src/main/java/com/supernova/fashionnova/security/JwtConstants.java, src/main/java/com/supernova/fashionnova/security/JwtUtil.java, src/main/java/com/supernova/fashionnova/security/UserDetailsImpl.java, src/main/java/com/supernova/fashionnova/security/UserDetailsServiceImpl.java, src/main/java/com/supernova/fashionnova/user/User.java, src/main/java/com/supernova/fashionnova/user/UserController.java, src/main/java/com/supernova/fashionnova/user/UserGrade.java, src/main/java/com/supernova/fashionnova/user/UserRepository.java, src/main/java/com/supernova/fashionnova/user/UserService.java, src/main/java/com/supernova/fashionnova/user/UserStatus.java, src/main/java/com/supernova/fashionnova/user/dto/LoginRequest.java, src/main/java/com/supernova/fashionnova/user/dto/LoginRequestDto.java, src/main/java/com/supernova/fashionnova/user/dto/SignupRequestDto.java, src/main/resources/application.properties, src/test/java/api/user.http
제목 : [🎉FEATURE] ] 회원가입,로그인 기능 구현
feat(issue 번호): 1
resolved: #2 , resolved: #3 
회원가입 기능 구현 완료
로그인 기능 구현 완료
UserStatus 이넘 수정,
UserGrade 이넘 수정
security,jwt 생성
build.gradle에 JWT 부분 추가
- 로그아웃
- 회원탈퇴
=> 1 feature user signup login

src/main/java/com/supernova/fashionnova/global/config/AppConfig.java, src/main/resources/application.properties, src/main/resources/properties/env.properties
제목 : 🎉 FEAT(환경변수): 환경변수 파일 env.proporties, AppConfig 생성
feat(issue 번호): 32
resolved: #32 
환경변수 파일 env.proporties, AppConfig 생성
DB_URL 전체 URL로 수정
-
=> 🎉 FEAT(환경변수): 환경변수 파일 env.proporties, AppConfig 생성

.gitignore, src/main/java/com/supernova/fashionnova/user/User.java, src/main/java/com/supernova/fashionnova/user/UserController.java, src/main/java/com/supernova/fashionnova/user/UserGrade.java, src/main/java/com/supernova/fashionnova/user/UserStatus.java, src/main/java/com/supernova/fashionnova/user/dto/LoginRequestDto.java, src/main/java/com/supernova/fashionnova/user/dto/SignupRequestDto.java
제목 : [🎉FEATURE] ] git 이그노어 수정
환경변수 프로포티 이그노어
=> [🎉FEATURE] ] git 이그노어 수정

build.gradle, src/main/java/com/supernova/fashionnova/global/config/JpaAuditingConfig.java, src/main/java/com/supernova/fashionnova/product/Product.java, src/main/java/com/supernova/fashionnova/product/ProductController.java, src/main/java/com/supernova/fashionnova/product/ProductRepository.java, src/main/java/com/supernova/fashionnova/product/ProductRepositoryQuery.java, src/main/java/com/supernova/fashionnova/product/ProductRepositoryQueryImpl.java, src/main/java/com/supernova/fashionnova/product/ProductService.java, src/main/java/com/supernova/fashionnova/product/dto/ProductResponseDto.java, src/main/resources/application.properties, src/test/java/api/product.http
제목 : [🎉FEATURE] 조건별 상품 검색 기능 구현 완료
feat(issue 번호): 20
resolved: #21 
resolved: #22 
resolved: #23 
resolved: #24 
resolved: #25 
상품검색(높/ 낮은 가격순)
상품검색(판매순)
상품검색(리뷰많은순)
상품검색(신상품순)
상품검색(카테고리별)
-
=> 조건별 상품 검색 기능 구현 완료

build.gradle, src/main/java/com/supernova/fashionnova/global/config/WebSecurityConfig.java, src/main/java/com/supernova/fashionnova/global/exception/ErrorType.java, src/main/java/com/supernova/fashionnova/global/exception/GlobalExceptionHandler.java, src/main/java/com/supernova/fashionnova/order/OrdersRepository.java, src/main/java/com/supernova/fashionnova/product/dto/ProductResponseDto.java, src/main/java/com/supernova/fashionnova/review/Review.java, src/main/java/com/supernova/fashionnova/review/ReviewController.java, src/main/java/com/supernova/fashionnova/review/ReviewImage.java, src/main/java/com/supernova/fashionnova/review/ReviewImageRepository.java, src/main/java/com/supernova/fashionnova/review/ReviewRepository.java, src/main/java/com/supernova/fashionnova/review/ReviewService.java, src/main/java/com/supernova/fashionnova/review/dto/MyReviewResponseDto.java, src/main/java/com/supernova/fashionnova/review/dto/ReviewDeleteRequestDto.java, src/main/java/com/supernova/fashionnova/review/dto/ReviewRequestDto.java, src/main/java/com/supernova/fashionnova/review/dto/ReviewResponseDto.java, src/main/java/com/supernova/fashionnova/review/dto/ReviewUpdateRequestDto.java, src/main/java/com/supernova/fashionnova/security/JwtAuthorizationFilter.java, src/test/java/api/review.http
제목 : [🎉FEATURE] ] 리뷰 CRUD
feat(issue 번호): #39
resolved: #41, resolved: #52, resolved: #51, resolved: #59, resolved: #60
내가 구매한 상품에 대한 리뷰 작성
상품에 대한 리뷰 전체 조회(비회원도 가능), 페이징
내가 작성한 리뷰 전체 조회, 페이징
리뷰 수정
리뷰 삭제
=> 39 review crud

src/main/java/com/supernova/fashionnova/user/User.java, src/main/java/com/supernova/fashionnova/user/UserService.java, src/main/java/com/supernova/fashionnova/user/dto/SignupRequestDto.java, src/main/java/com/supernova/fashionnova/user/dto/UserUpdateRequestDto.java, src/test/java/com/supernova/fashionnova/FashionNovaApplicationTests.java, src/test/java/com/supernova/fashionnova/user/UserControllerTest.java, src/test/java/com/supernova/fashionnova/user/UserServiceTest.java
제목 :[🍻 TEST] 유저 서비스, 유저 컨트룰러 테스트 코드
feat(issue 번호): 53
resolved: #54 , resolved: #56  ,resolved: #55 
유저 컨트룰러 회원가입,로그아웃 완료
유저 컨트룰러 테스트 진행중
유저 서비스 테스트 구현 완료
@SpringBootTest 때문에 빌드가 안되던 문제 발생
- 문의 테스트 구현
=> [🍻 TEST] 유저 서비스, 유저 컨트룰러 테스트 코드

src/main/java/com/supernova/fashionnova/question/Question.java, src/main/java/com/supernova/fashionnova/question/dto/QuestionRequestDto.java, src/main/java/com/supernova/fashionnova/user/User.java, src/main/java/com/supernova/fashionnova/user/UserService.java, src/main/java/com/supernova/fashionnova/user/dto/SignupRequestDto.java, src/main/java/com/supernova/fashionnova/user/dto/UserUpdateRequestDto.java, src/test/java/com/supernova/fashionnova/FashionNovaApplicationTests.java, src/test/java/com/supernova/fashionnova/question/QuestionControllerTest.java, src/test/java/com/supernova/fashionnova/question/QuestionServiceTest.java, src/test/java/com/supernova/fashionnova/user/UserControllerTest.java, src/test/java/com/supernova/fashionnova/user/UserServiceTest.java
제목 : [🍻TEST] 문의 서비스,컨트룰러 테스트 구현 완료
feat(issue 번호): 72
resolved: #73 , resolved: #74 
문의 서비스 테스트 구현 완료
의 컨트룰러 테스트 구현 완료
문의 등록 테스트
문의 조회 테스트
FIX(UserRequestDto): Password 정규식 수정
-
=>  [🍻TEST] 문의 서비스,컨트룰러 테스트 구현 완료

src/main/java/com/supernova/fashionnova/coupon/Coupon.java, src/main/java/com/supernova/fashionnova/coupon/CouponController.java, src/main/java/com/supernova/fashionnova/coupon/CouponService.java, src/main/java/com/supernova/fashionnova/coupon/dto/CouponRequestDto.java, src/test/java/com/supernova/fashionnova/address/AddressControllerTest.java, src/test/java/com/supernova/fashionnova/address/AddressServiceTest.java, src/test/java/com/supernova/fashionnova/coupon/CouponControllerTest.java, src/test/java/com/supernova/fashionnova/coupon/CouponServiceTest.java
제목 : [🍻TEST] 쿠폰 조회 테스트 완료
feat(issue 번호): #78
resolved: #79, resolved: #80
- 쿠폰 엔티티 생성자 메서드 추가
- 배송지 테스트 리팩토링
- 위시리스트 서비스 테스트
- 위시리스트 컨트롤러 테스트
=> [🍻TEST] 쿠폰 조회 테스트 완료

src/main/java/com/supernova/fashionnova/cart/dto/CartDeleteRequestDto.java, src/main/java/com/supernova/fashionnova/cart/dto/CartRequestDto.java, src/main/java/com/supernova/fashionnova/cart/dto/CartUpdateRequestDto.java, src/test/java/com/supernova/fashionnova/cart/CartControllerTest.java, src/test/java/com/supernova/fashionnova/cart/CartServiceTest.java
제목 : [🎉FEATURE] ] / [♻️ REFACTOR] 카트 
feat(issue 번호): #66
resolved: #66, resolved: #67,  resolved: #69
카트 서비스, 컨트롤러 테스트 코드 작성
RequestDto에 생성자 추가
- 리뷰 서비스 테스트 코드 작성, 리뷰 컨트롤러 테스트 코드 작성
=> 66 feature cart test

src/main/java/com/supernova/fashionnova/admin/AdminController.java, src/main/java/com/supernova/fashionnova/admin/AdminService.java, src/test/java/api/admin.http
제목 : [🎉FEATURE] 작성자별 리뷰 조회 (admin) 기능 구현
feat(issue 번호): #94 
resolved: #94, resolved: #95
작성자별 리뷰 조회 (admin) 기능 구현
작성한 리뷰가 없을 때 빈 List 출력
- 작성자별 리뷰 조회 (admin) 컨트롤러 테스트
- 작성자별 리뷰 조회 (admin) 서비스 테스트
=> [🎉FEATURE] 작성자별 리뷰 조회 (admin) 기능 구현

build.gradle, src/main/resources/application-test.properties, src/main/resources/application.properties, src/test/java/com/supernova/fashionnova/product/ProductControllerTest.java, src/test/java/com/supernova/fashionnova/product/ProductRepositoryQueryImplTest.java, src/test/java/com/supernova/fashionnova/product/ProductServiceTest.java
제목 : [🎉FEATURE] 조건 별 상품 검색 테스트 코드 작성
조건 별 상품 검색 테스트 코드 작성
=>  FEAT(상품): 조건 별 상품 검색 테스트 코드 작성

src/main/java/com/supernova/fashionnova/admin/AdminController.java, src/main/java/com/supernova/fashionnova/admin/AdminService.java, src/main/java/com/supernova/fashionnova/cart/CartService.java, src/main/java/com/supernova/fashionnova/product/Product.java, src/main/java/com/supernova/fashionnova/product/ProductController.java, src/main/java/com/supernova/fashionnova/product/ProductDetail.java, src/main/java/com/supernova/fashionnova/product/ProductRepositoryQueryImpl.java, src/main/java/com/supernova/fashionnova/product/dto/ProductDetailRequestDto.java, src/main/java/com/supernova/fashionnova/product/dto/ProductRequestDto.java, src/main/java/com/supernova/fashionnova/product/dto/ProductResponseDto.java, src/test/java/com/supernova/fashionnova/cart/CartServiceTest.java
제목 : [🎉FEATURE] 어드민 상품 등록 / 상품 등록 테스트 코드
feat(issue 번호): #99 
resolved: #100 
어드민 상품 등록 / 테스트
=> 🎉 FEAT: 어드민 상품 등록 / 상품 등록 테스트 코드

src/main/java/com/supernova/fashionnova/address/AddressController.java, src/main/java/com/supernova/fashionnova/address/AddressService.java, src/main/java/com/supernova/fashionnova/admin/AdminController.java, src/main/java/com/supernova/fashionnova/admin/AdminService.java, src/main/java/com/supernova/fashionnova/answer/Answer.java, src/main/java/com/supernova/fashionnova/answer/AnswerRepository.java, src/main/java/com/supernova/fashionnova/answer/dto/AnswerRequestDto.java, src/main/java/com/supernova/fashionnova/global/common/Timestamped.java, src/main/java/com/supernova/fashionnova/global/exception/ErrorType.java, src/main/java/com/supernova/fashionnova/order/Order.java, src/main/java/com/supernova/fashionnova/product/dto/ProductResponseDto.java, src/main/java/com/supernova/fashionnova/question/QuestionController.java, src/main/java/com/supernova/fashionnova/question/QuestionRepository.java, src/main/java/com/supernova/fashionnova/question/QuestionService.java, src/main/java/com/supernova/fashionnova/review/Review.java, src/main/java/com/supernova/fashionnova/review/ReviewController.java, src/main/java/com/supernova/fashionnova/review/ReviewService.java, src/main/java/com/supernova/fashionnova/security/UserDetailsImpl.java, src/main/java/com/supernova/fashionnova/user/UserService.java, src/main/java/com/supernova/fashionnova/wish/WishController.java, src/main/java/com/supernova/fashionnova/wish/WishService.java, src/test/java/api/admin.http, src/test/java/com/supernova/fashionnova/address/AddressControllerTest.java, src/test/java/com/supernova/fashionnova/address/AddressServiceTest.java, src/test/java/com/supernova/fashionnova/admin/AdminControllerTest.java, src/test/java/com/supernova/fashionnova/admin/AdminServiceTest.java, src/test/java/com/supernova/fashionnova/question/QuestionControllerTest.java, src/test/java/com/supernova/fashionnova/question/QuestionServiceTest.java, src/test/java/com/supernova/fashionnova/wish/WishControllerTest.java, src/test/java/com/supernova/fashionnova/wish/WishServiceTest.java
제목 : [🎉FEATURE] 어드민 답변 등록 문의 조회
feat(issue 번호): #102
resolved: #103, resolved: #104
어드민 답변 등록
어드민 전제 문의 조회
- 문의 조회 시 답변도 보이게 수정
- 상품에서 위시와 리뷰 카운트 올라가는 로직 추가
- 어드민 컨트롤러 서비스 테스트
=> [🎉FEATURE] 어드민 답변 등록 문의 조회

src/main/java/com/supernova/fashionnova/address/AddressController.java, src/main/java/com/supernova/fashionnova/admin/AdminController.java, src/main/java/com/supernova/fashionnova/admin/AdminService.java, src/main/java/com/supernova/fashionnova/coupon/Coupon.java, src/main/java/com/supernova/fashionnova/coupon/CouponController.java, src/main/java/com/supernova/fashionnova/coupon/CouponService.java, src/main/java/com/supernova/fashionnova/coupon/dto/CouponRequestDto.java, src/main/java/com/supernova/fashionnova/global/exception/ErrorType.java, src/main/java/com/supernova/fashionnova/product/Product.java, src/main/java/com/supernova/fashionnova/product/ProductController.java, src/main/java/com/supernova/fashionnova/product/ProductService.java, src/main/java/com/supernova/fashionnova/product/dto/ProductResponseDto.java, src/main/java/com/supernova/fashionnova/question/QuestionController.java, src/main/java/com/supernova/fashionnova/review/ReviewService.java, src/main/java/com/supernova/fashionnova/user/UserController.java, src/main/java/com/supernova/fashionnova/wish/WishController.java, src/main/java/com/supernova/fashionnova/wish/WishRepository.java, src/main/java/com/supernova/fashionnova/wish/WishService.java, src/test/java/api/admin.http
제목 : [🎉FEATURE] 어드민 쿠폰 지급
feat(issue 번호): #122
resolved: #123
쿠폰 지급
- 어드민 컨트롤러 서비스 테스트
=> [🎉FEATURE] 어드민 쿠폰 지급

src/main/java/com/supernova/fashionnova/admin/AdminService.java, src/main/java/com/supernova/fashionnova/product/ProductImage.java, src/main/java/com/supernova/fashionnova/product/ProductImageRepository.java, src/main/java/com/supernova/fashionnova/question/QuestionImage.java, src/main/java/com/supernova/fashionnova/question/QuestionImageRepository.java, src/main/java/com/supernova/fashionnova/question/QuestionService.java, src/main/java/com/supernova/fashionnova/review/ReviewController.java, src/main/java/com/supernova/fashionnova/review/ReviewImage.java, src/main/java/com/supernova/fashionnova/review/ReviewImageRepository.java, src/main/java/com/supernova/fashionnova/review/ReviewRepository.java, src/main/java/com/supernova/fashionnova/review/ReviewService.java, src/main/java/com/supernova/fashionnova/upload/FileUploadUtil.java
제목 : [🎉FEATURE] 파일 조회 삭제
feat(issue 번호): #97 
리뷰, 상품,문의레포지 토리에 키값 추가
키값을 통해 s3에서 조회 기능 구현
리뷰 이미지 삭제, s3에서 삭제 구현 완료
- 프론트 작업
=> [🎉FEATURE] 파일 조회 삭제

src/main/java/com/supernova/fashionnova/admin/AdminController.java, src/main/java/com/supernova/fashionnova/admin/AdminService.java, src/main/java/com/supernova/fashionnova/mileage/Mileage.java, src/main/java/com/supernova/fashionnova/mileage/MileageController.java, src/main/java/com/supernova/fashionnova/mileage/MileageService.java, src/main/java/com/supernova/fashionnova/mileage/dto/MileageRequestDto.java, src/main/java/com/supernova/fashionnova/mileage/dto/MileageResponseDto.java, src/main/java/com/supernova/fashionnova/order/OrderDetail.java, src/main/java/com/supernova/fashionnova/order/OrdersRepository.java, src/test/java/api/admin.http, src/test/java/api/mileage.http, src/test/java/com/supernova/fashionnova/admin/AdminControllerTest.java, src/test/java/com/supernova/fashionnova/admin/AdminServiceTest.java, src/test/java/com/supernova/fashionnova/mileage/MileageControllerTest.java, src/test/java/com/supernova/fashionnova/mileage/MileageServiceTest.java
제목 : [🎉FEATURE] 마일리지 기능 구현
feat(issue 번호): #132
resolved: #133, resolved: #134, resolved: #135
어드민 마일리지 지급
어드민 마일리지 초기화
유저 마일리지 내역 조회
테스트 코드까지
Order 엔티티에 extends Timestamped
- 리팩토링
- CI/CD
=> [🎉FEATURE] 마일리지 기능 구현

docker/Dockerfile, src/main/java/com/supernova/fashionnova/wish/WishService.java, src/test/java/com/supernova/fashionnova/admin/AdminServiceTest.java, src/test/java/com/supernova/fashionnova/question/QuestionControllerTest.java, src/test/java/com/supernova/fashionnova/question/QuestionServiceTest.java, src/test/java/com/supernova/fashionnova/review/ReviewControllerTest.java, src/test/java/com/supernova/fashionnova/wish/WishControllerTest.java, src/test/java/com/supernova/fashionnova/wish/WishServiceTest.java
제목 : [🎉FEATURE] 도커파일
feat(issue 번호): #141
resolved: #142
도커파일 추가
테스트 코드 주석처리
- 테스트 코드
- 리팩토링
=> [🎉FEATURE] 도커파일

src/main/java/com/supernova/fashionnova/global/config/WebSecurityConfig.java, src/main/resources/templates/about.html, src/main/resources/templates/contact.html, src/main/resources/templates/my-page.html, src/main/resources/templates/question.html
=> 🎉 FEAT(프론트): 프론트 오류로 배포 안되던 문제 헤결

src/test/java/com/supernova/fashionnova/user/UserControllerTest.java
테스트 코드 오류로 배포 안되던 문제 해결
프론트 생성으로 결과값이 "redirect:/login"으로 바귐
=> 🐞 FIX(테스트코드): 테스트 코드 오류로 배포 안되던 문제 해결

src/main/java/com/supernova/fashionnova/security/JwtUtil.java, src/main/java/com/supernova/fashionnova/user/KakaoService.java, src/main/java/com/supernova/fashionnova/user/User.java, src/main/java/com/supernova/fashionnova/user/UserController.java
제목 :♻️ REFACTOR: 카카오 소셜 로그인(add refreshToken)
feat(issue 번호): #이슈번호
resolved: #146 , resolved: #이슈번호
-
=> ♻️ REFACTOR: 카카오 소셜 로그인(add refreshToken)

src/main/java/com/supernova/fashionnova/address/AddressController.java, src/main/java/com/supernova/fashionnova/address/AddressService.java, src/main/java/com/supernova/fashionnova/address/dto/AddressDeleteRequestDto.java, src/main/java/com/supernova/fashionnova/global/exception/ErrorType.java, src/test/java/api/address.http
제목 : [🎉FEATURE] 배송지 삭제
배송지 삭제
- 프론트 좋아요 연결
=> [🎉FEATURE] 배송지 삭제

src/main/java/com/supernova/fashionnova/admin/AdminController.java, src/main/java/com/supernova/fashionnova/cart/Cart.java, src/main/java/com/supernova/fashionnova/global/common/MileageScheduler.java, src/main/java/com/supernova/fashionnova/global/config/JpaAuditingConfig.java, src/main/java/com/supernova/fashionnova/global/faker/DataGenerator.java, src/main/java/com/supernova/fashionnova/global/faker/DataInitializer.java, src/main/java/com/supernova/fashionnova/product/Product.java, src/main/java/com/supernova/fashionnova/review/Review.java, src/main/java/com/supernova/fashionnova/user/User.java, src/main/java/com/supernova/fashionnova/warn/Warn.java, src/test/java/com/supernova/fashionnova/product/ProductRepositoryQueryImplTest.java
제목 : [♻️ REFACTOR] 엔티티 리팩토링
엔티티 리팩토링
마일리지 분기별 삭제
레퍼지토리 테스트 주석처리
- 레포지터리 리팩토링
- 디티오 리팩토링
=> [♻️ REFACTOR] 엔티티 리팩토링

src/main/java/com/supernova/fashionnova/domain/wish/WishController.java, src/main/java/com/supernova/fashionnova/domain/wish/WishService.java, src/main/java/com/supernova/fashionnova/domain/wish/dto/WishResponseDto.java
제목 : [🐞BUG] 위시리스트 조회
WishResponseDto 생성
-
-
=> [🐞BUG] 위시리스트 조회

src/main/java/com/supernova/fashionnova/domain/address/dto/AddressResponseDto.java, src/main/resources/templates/my-info.html, src/main/resources/templates/wish-list.html
제목 : [🎉FEATURE] 프론트 연결 장바구니-유저 정보
feat(issue 번호): #164 
resolved: #165, resolved: #166
my-info , shopingcart, wishlist 페이지 작업
장바구니,위시리스트 개수 조회
default 0 -> ""
모든페이지에서 My Page 버튼 누를시 이동하도록 수정
쇼핑카트 페이지에서 상품 리스트 DB에서 불러와서 붙여넣기 구현완료
카트- 백- 프론트 연결 DB에서 카트 조회해서 프론트에 붙이기 성공
위시리스트- 백- 프론트 연결 DB에서 위시리스트 조회해서 상품 프론트에 붙이기 성공
장바구니에서 상품 개별 삭제 구현 완료
장바구니 비우기 성공
장바구니 수량변동 버튼 성공
로그인 안되어있으면 alter로 undifined 나오던거 콘솔로 수정
배송지 모달 및 도로명 주소 찾기 구현 완료
배송지 로드 연결성공
배송지 추가(POST) 연결성공
: 기본 배송지 업데이트 완료
배송지 삭제 구현 완료
회원정보 수정하기 기능구현 및 백앤드 연결완료
원탈퇴 기능구현 및 백앤드 연결완료
위시리스트 삭제 구현 완료
🐞FIX(my-info): 로그인 안되어있으면 로그인 페이지로 옮기기
🐞 FIX(my-info): 배송지 추가 유효성 검사 로직 추가
-
=>  [🎉FEATURE] 프론트 연결 장바구니-유저 정보

src/main/java/com/supernova/fashionnova/domain/cart/CartService.java, src/main/java/com/supernova/fashionnova/domain/cart/dto/CartItemDto.java, src/main/java/com/supernova/fashionnova/domain/cart/dto/CartResponseDto.java, src/main/java/com/supernova/fashionnova/domain/coupon/dto/CouponResponseDto.java, src/main/java/com/supernova/fashionnova/domain/question/dto/QuestionResponseDto.java, src/main/java/com/supernova/fashionnova/domain/user/dto/UserResponseDto.java, src/main/java/com/supernova/fashionnova/domain/warn/dto/WarnResponseDto.java, src/main/java/com/supernova/fashionnova/domain/wish/dto/WishResponseDto.java, src/test/java/com/supernova/fashionnova/wish/WishControllerTest.java, src/test/java/com/supernova/fashionnova/wish/WishServiceTest.java
제목 : [♻️ REFACTOR] 리스폰스 id 달아주기
리스폰스에 id 달아주기
wish 리스폰스 wishId -> id
수정해야할 테스트 코드 주석
- 
-
=> [♻️ REFACTOR] 리스폰스 id 달아주기

src/main/java/com/supernova/fashionnova/global/upload/FileUploadUtil.java, src/main/resources/static/js/login.js, src/main/resources/templates/login.html, src/main/resources/templates/order.html, src/main/resources/templates/review.html
제목 : [🎉FEATURE] 프론드-리뷰-qana 연결
리뷰 페이지에 내가 작성한 리뷰 동적으로 추가하기 구현
리뷰 삭제 구현
🎉 FEAT(order.html): 카트,찜 개수 세기 추가
로그인 할때 어디서든 엔터누르면 로그인 버튼
=>  [🎉FEATURE] 프론드-리뷰-qana 연결

src/main/java/com/supernova/fashionnova/domain/product/ProductController.java, src/main/java/com/supernova/fashionnova/domain/product/ProductService.java
제목 :🐞 FIX: 조건별 상품 조회 프론트 (버그 수정)
feat(issue 번호): #이슈번호
버그 수정
=> 🐞 FIX: 조건별 상품 조회 프론트 (버그 수정)

.github/workflows/cd.yml, src/main/java/com/supernova/fashionnova/admin/AdminService.java, src/main/java/com/supernova/fashionnova/domain/answer/dto/AnswerResponseDto.java, src/main/java/com/supernova/fashionnova/domain/order/dto/OrderDetailResponseDto.java, src/main/java/com/supernova/fashionnova/domain/question/Question.java, src/main/java/com/supernova/fashionnova/domain/question/QuestionController.java, src/main/java/com/supernova/fashionnova/domain/question/QuestionRepository.java, src/main/java/com/supernova/fashionnova/domain/question/QuestionService.java, src/main/java/com/supernova/fashionnova/domain/question/dto/QuestionDetailResponseDto.java, src/main/java/com/supernova/fashionnova/domain/question/dto/QuestionRequestDto.java, src/main/java/com/supernova/fashionnova/domain/review/ReviewController.java, src/main/java/com/supernova/fashionnova/global/exception/ErrorType.java, src/main/java/com/supernova/fashionnova/global/faker/DataGenerator.java, src/test/java/api/admin.http, src/test/java/api/question.http, src/test/java/api/user.http, src/test/java/com/supernova/fashionnova/admin/AdminServiceTest.java, src/test/java/com/supernova/fashionnova/question/QuestionControllerTest.java, src/test/java/com/supernova/fashionnova/question/QuestionServiceTest.java
제목 : [🐞BUG] 문의 기능 수정
문의 기능 수정
답변 기능 수정
배포 파일 수정
- 이메일 인증
=> [🐞BUG] 문의 기능 수정

src/main/java/com/supernova/fashionnova/domain/product/ProductService.java, src/main/java/com/supernova/fashionnova/payment/KakaoPayController.java, src/main/java/com/supernova/fashionnova/payment/KakaoPayService.java, src/test/java/api/order.http, src/test/java/api/payment.http
제목 : [[♻️ REFACTOR]
feat(issue 번호): #11
별거 아니구 장바구니 비우기 메서드 주석해제하고 지워졌던 cartService 추가했습니당
-
=> 11 feature payment kakaopay 수정

src/main/resources/templates/order-detail.html, src/main/resources/templates/order.html, src/main/resources/templates/product-detail.html, src/main/resources/templates/review.html
[♻️ REFACTOR] 리뷰 오더 페이지 모달 수정
feat(issue 번호): #207 
오더, 오더 디테일 페이지 주문 취소/환불/교환 문의 모달에 제목 입력하는 input 박스 추가
My Review 페이지 Edit버튼에 모달 추가
=>  [♻️ REFACTOR] 리뷰 오더 페이지 모달 수정

.github/workflows/cd.yml, build.gradle, src/main/java/com/supernova/fashionnova/global/config/WebSecurityConfig.java, src/main/java/com/supernova/fashionnova/global/mail/MailController.java, src/main/java/com/supernova/fashionnova/global/mail/MailService.java, src/main/resources/application.properties
제목 : [🎉FEATURE] 이메일 인증
feat(issue 번호): #203
resolved: #203
이메일 인증 기능 구현
이메일 인증 권한 설정
환경 변수 추가
배포 자료 수정
- 이것저것
=> [🎉FEATURE] 이메일 인증

src/main/java/com/supernova/fashionnova/admin/AdminController.java, src/main/java/com/supernova/fashionnova/admin/AdminService.java, src/main/java/com/supernova/fashionnova/domain/mileage/MileageService.java, src/main/java/com/supernova/fashionnova/domain/order/OrderRepositoryQuery.java, src/main/java/com/supernova/fashionnova/domain/order/OrderRepositoryQueryImpl.java, src/main/java/com/supernova/fashionnova/domain/order/OrdersRepository.java, src/main/java/com/supernova/fashionnova/global/exception/ErrorType.java, src/test/java/api/admin.http, src/test/java/api/order.http, src/test/java/api/payment.http
판매통계 일별, 주별, 월별 생성
제목 : [🎉FEATURE]
feat(issue 번호): #11
-
=> 🎉 FEAT(admin): 판매통계

.github/workflows/cd.yml, src/main/java/com/supernova/fashionnova/domain/question/Question.java, src/main/java/com/supernova/fashionnova/domain/question/dto/QuestionDetailResponseDto.java, src/test/java/com/supernova/fashionnova/admin/AdminControllerTest.java
제목 : [🐞BUG] 연관 관계 수정
orders_details 와 question 의 관계 수정
- 테스트 코드 수정
- 리팩토링
- Redis 연결
=> 🐞 FIX(문의): 관계 수정

src/main/java/com/supernova/fashionnova/admin/AdminController.java, src/main/java/com/supernova/fashionnova/admin/AdminService.java, src/main/java/com/supernova/fashionnova/admin/dto/AllReviewResponseDto.java, src/main/java/com/supernova/fashionnova/admin/dto/UserProfileResponseDto.java, src/main/java/com/supernova/fashionnova/admin/dto/UsersCouponAndMileageResponseDto.java, src/main/java/com/supernova/fashionnova/domain/cart/CartController.java, src/main/java/com/supernova/fashionnova/domain/question/QuestionController.java, src/main/java/com/supernova/fashionnova/domain/question/QuestionService.java, src/main/java/com/supernova/fashionnova/domain/user/UserController.java, src/main/java/com/supernova/fashionnova/domain/user/UserService.java, src/test/java/com/supernova/fashionnova/admin/AdminServiceTest.java, src/test/java/com/supernova/fashionnova/question/QuestionControllerTest.java, src/test/java/com/supernova/fashionnova/question/QuestionServiceTest.java
제목 : [🐞BUG] 테스트 코드
답변 등록 테스트
문의 등록 테스트
내 문의 조회 테스트
문의 상세 조회 테스트
어드민 리팩토링
- 리팩토링
=> [🐞BUG] 테스트 코드, 어드민 리팩토링

src/main/resources/templates/product-detail.html, src/main/resources/templates/product.html
제목 : [🎉FEATURE] 상품조회 프론트
feat(issue 번호): #236 
resolved: #236
Load More 버튼 기능 구현
=> [🎉FEATURE] 상품조회 프론트

src/main/java/com/supernova/fashionnova/domain/order/OrderService.java, src/main/java/com/supernova/fashionnova/domain/order/dto/AllOrderResponseDto.java
[♻️ REFACTOR] 코드 리펙토링
feat(issue 번호): #222
resolved: #222, resolved: #223
AllOrderResponseDto에 생성자 추가
=> ♻️ REFACTOR: AllOrderResponseDto에 생성자 추가

src/main/java/com/supernova/fashionnova/admin/AdminService.java, src/main/java/com/supernova/fashionnova/domain/warn/WarnRepository.java, src/test/java/api/admin.http
제목 : [🐞BUG] 유저 경고 로직 수정
경고가 3번이 되면 블랙리스트로 등록
- 테스트
=> [🐞BUG] 유저 경고 로직 수정

src/main/java/com/supernova/fashionnova/domain/coupon/Coupon.java, src/main/java/com/supernova/fashionnova/domain/coupon/CouponRepository.java, src/main/java/com/supernova/fashionnova/domain/coupon/CouponService.java, src/main/java/com/supernova/fashionnova/domain/coupon/dto/CouponRequestDto.java, src/main/java/com/supernova/fashionnova/domain/user/UserService.java, src/test/java/api/admin.http, src/test/java/api/user.http, src/test/java/com/supernova/fashionnova/admin/AdminControllerTest.java, src/test/java/com/supernova/fashionnova/product/ProductServiceTest.java, src/test/java/com/supernova/fashionnova/review/ReviewControllerTest.java, src/test/java/com/supernova/fashionnova/review/ReviewServiceTest.java, src/test/java/com/supernova/fashionnova/user/UserServiceTest.java, src/test/java/com/supernova/fashionnova/wish/WishControllerTest.java, src/test/java/com/supernova/fashionnova/wish/WishServiceTest.java
제목 : [🐞BUG] 쿠폰 기간
쿠폰 기간이 지나면 조회하기 전 상태를 INACTIVE 로 수정
- 테스트
=> [🐞BUG] 쿠폰 기간

src/main/java/com/supernova/fashionnova/domain/coupon/CouponService.java, src/test/java/com/supernova/fashionnova/order/OrderControllerTest.java, src/test/java/com/supernova/fashionnova/order/OrderDetailControllerTest.java, src/test/java/com/supernova/fashionnova/order/OrderServiceTest.java
=> [🐞BUG] 빌드 오류 해결

src/main/resources/templates/product-detail.html, src/main/resources/templates/question.html
[♻️ REFACTOR] 파일업로드 이미지만 가능하도록 변경
♻️ REFACTOR: 파일업로드 이미지만 가능하도록 변경
=> [♻️ REFACTOR] 파일업로드 이미지만 가능하도록 변경

src/main/java/com/supernova/fashionnova/domain/coupon/CouponService.java, src/main/java/com/supernova/fashionnova/domain/order/OrderDetailController.java, src/test/java/com/supernova/fashionnova/order/OrderControllerTest.java, src/test/java/com/supernova/fashionnova/order/OrderDetailControllerTest.java
제목 : [🎉FEATURE] / [♻️ REFACTOR] / [🐞BUG] / [🍻TEST] + 제목을 입력해주세요
feat(issue 번호): #11
-
=> 🍻 TEST(orderDetailTest): 테스트 코드 추가

src/main/java/com/supernova/fashionnova/domain/coupon/CouponService.java, src/main/java/com/supernova/fashionnova/domain/wish/Wish.java, src/main/java/com/supernova/fashionnova/domain/wish/WishRepository.java, src/main/java/com/supernova/fashionnova/domain/wish/WishService.java, src/test/java/api/wish.http
제목 : [♻️ REFACTOR] 위시 최신순 정렬 조회
[♻️ REFACTOR] 위시 최신순 정렬 조회
- 배포
=> [♻️ REFACTOR] 위시 최신순 정렬 조회

src/main/resources/templates/about.html, src/main/resources/templates/contact.html, src/main/resources/templates/grade.html, src/main/resources/templates/index.html, src/main/resources/templates/my-coupon.html, src/main/resources/templates/my-info.html, src/main/resources/templates/my-mileage.html, src/main/resources/templates/my-page.html, src/main/resources/templates/my-question-detail.html, src/main/resources/templates/my-question.html, src/main/resources/templates/order-detail.html, src/main/resources/templates/order.html, src/main/resources/templates/payment-one.html, src/main/resources/templates/payment.html, src/main/resources/templates/payments-completed.html, src/main/resources/templates/product-detail.html, src/main/resources/templates/product.html, src/main/resources/templates/question.html, src/main/resources/templates/review.html, src/main/resources/templates/shoping-cart.html, src/main/resources/templates/wish-list.html
♻️ REFACTOR: 불필요한 SNS 아이콘 제거
feat(issue 번호): #244 
♻️ REFACTOR: 불필요한 SNS 아이콘 제거
=> 244 bug 사용자 페이지 버그 수정

src/main/java/com/supernova/fashionnova/domain/review/ReviewController.java, src/main/java/com/supernova/fashionnova/domain/user/KakaoService.java, src/main/java/com/supernova/fashionnova/domain/user/UserController.java, src/main/java/com/supernova/fashionnova/global/security/JwtAuthorizationFilter.java, src/main/java/com/supernova/fashionnova/payment/KakaoPayController.java, src/main/java/com/supernova/fashionnova/payment/KakaoPayService.java, src/main/resources/templates/payment.html
제목 : [🐞BUG] 카카오페이 주소 배포된주소로 수정
=>  [🐞BUG] 카카오페이 주소 배포된주소로 수정

src/main/java/com/supernova/fashionnova/payment/KakaoPayController.java
제목 :♻️ REFACTOR(kakaopay): 배포된 서버에서 카카오 페이 성공했을 때 쿠폰아이디 주석
=> ♻️ REFACTOR(kakaopay): 배포된 서버에서 카카오 페이 성공했을 때 쿠폰아이디 주석

src/main/java/com/supernova/fashionnova/domain/coupon/CouponService.java, src/main/java/com/supernova/fashionnova/payment/KakaoPayController.java, src/main/java/com/supernova/fashionnova/payment/KakaoPayService.java, src/main/resources/templates/kakaopay.html
제목 : [🎉FEATURE] / [♻️ REFACTOR] / [🐞BUG] / [🍻TEST] + 제목을 입력해주세요
feat(issue 번호): #이슈번호11
-
=> 🐞 FIX(카카오페이): 쿠폰 적용 수정

src/main/generated/com/supernova/fashionnova/domain/address/QAddress.java, src/main/generated/com/supernova/fashionnova/domain/answer/QAnswer.java, src/main/generated/com/supernova/fashionnova/domain/cart/QCart.java, src/main/generated/com/supernova/fashionnova/domain/coupon/QCoupon.java, src/main/generated/com/supernova/fashionnova/domain/mileage/QMileage.java, src/main/generated/com/supernova/fashionnova/domain/order/QOrder.java, src/main/generated/com/supernova/fashionnova/domain/order/QOrderDetail.java, src/main/generated/com/supernova/fashionnova/domain/product/QProduct.java, src/main/generated/com/supernova/fashionnova/domain/product/QProductDetail.java, src/main/generated/com/supernova/fashionnova/domain/product/QProductImage.java, src/main/generated/com/supernova/fashionnova/domain/question/QQuestion.java, src/main/generated/com/supernova/fashionnova/domain/question/QQuestionImage.java, src/main/generated/com/supernova/fashionnova/domain/review/QReview.java, src/main/generated/com/supernova/fashionnova/domain/review/QReviewImage.java, src/main/generated/com/supernova/fashionnova/domain/user/QUser.java, src/main/generated/com/supernova/fashionnova/domain/warn/QWarn.java, src/main/generated/com/supernova/fashionnova/domain/wish/QWish.java, src/main/generated/com/supernova/fashionnova/global/common/QTimestamped.java, src/main/java/com/supernova/fashionnova/domain/order/OrderController.java, src/main/java/com/supernova/fashionnova/domain/order/OrderService.java, src/main/resources/templates/about.html, src/main/resources/templates/contact.html, src/main/resources/templates/grade.html, src/main/resources/templates/index.html, src/main/resources/templates/order-detail.html, src/main/resources/templates/product-detail.html, src/main/resources/templates/product.html, src/main/resources/templates/question.html, src/main/resources/templates/wish-list.html
제목 :  [♻️ REFACTOR] 유저테스트 중 수정
♻️ REFACTOR(oder-detail.html): 오더 디테일 페이지에서 계산 금액 수정
♻️ REFACTOR(question.html): 필드값 없을 때 예외처리
♻️ REFACTOR(wish.html): 페이징 처리
♻️ REFACTOR(일부페이지): 위시랑 카트 10개 넘으면 10+로 보이게 변경
=> [♻️ REFACTOR] 유저테스트 중 수정

src/main/java/com/supernova/fashionnova/domain/order/OrderDetailController.java, src/main/java/com/supernova/fashionnova/domain/order/OrdersRepository.java, src/main/java/com/supernova/fashionnova/domain/order/dto/AllOrderResponseDto.java, src/main/java/com/supernova/fashionnova/domain/order/dto/OrderDetailResponseDto.java, src/main/java/com/supernova/fashionnova/domain/product/ProductService.java, src/main/resources/templates/index.html, src/main/resources/templates/my-info.html, src/main/resources/templates/order-detail.html, src/main/resources/templates/product.html
제목 :  [🐞BUG] 상품조회, 상품디테일 에러수정
feat(issue 번호): #251 
resolved: #251 
[🐞 FIX: 충돌 해결 및 카테고리 선택 시 찜 에러 수정]
[🐞 FIX: 리뷰 등록 에러 수정]
[🐞 FIX: 비로그인 상태에서 찜 눌렀을 때 동작 추가]
=>  [🐞BUG] 상품조회, 상품디테일 에러수정

src/main/resources/templates/my-coupon.html, src/main/resources/templates/my-mileage.html, src/main/resources/templates/my-question.html, src/main/resources/templates/order.html, src/main/resources/templates/payment-one.html, src/main/resources/templates/payment.html, src/main/resources/templates/product-detail.html, src/main/resources/templates/product.html, src/main/resources/templates/review.html, src/main/resources/templates/warn.html
[♻️ REFACTOR] 경고메시지, 얼럿창 버그, 페이지 최신순 정렬
경고 메시지 수정
쿠폰, 마일리지, 오더, 리뷰, Q&A 페이지 최신순 정렬
=>  [♻️ REFACTOR] 경고메시지, 얼럿창 버그, 페이지 최신순 정렬

src/main/java/com/supernova/fashionnova/domain/mileage/MileageService.java, src/main/java/com/supernova/fashionnova/domain/order/OrderService.java, src/main/java/com/supernova/fashionnova/domain/order/OrderStatus.java, src/main/java/com/supernova/fashionnova/domain/order/dto/OrderRequestDto.java, src/main/java/com/supernova/fashionnova/domain/product/ProductService.java, src/main/java/com/supernova/fashionnova/global/exception/ErrorType.java, src/main/java/com/supernova/fashionnova/payment/KakaoPayController.java, src/main/java/com/supernova/fashionnova/payment/KakaoPayService.java, src/main/resources/templates/payment.html, src/main/resources/templates/payments-failed.html, src/test/java/api/user.http
결제 중단 시 redirect 페이지 생성
실패한 주문 삭제 시점 수정
orderStatus enum 수정
무한결제 수정
order 계산 로직 삭제
제목 :[🐞BUG] 
feat(issue 번호): #11
-
=> 🐞 FIX(버그 수정): order

.github/workflows/cd.yml, src/main/java/com/supernova/fashionnova/payment/KakaoPayService.java, src/main/resources/application.properties, src/main/resources/templates/order-detail.html
♻️ REFACTOR(환경변수): 주소 로컬/배포된주소 환경변수로 추가
order-status enum 대문자 안되어있던거 DB에서 직접 수정
=> ♻️ REFACTOR(환경변수): 주소 로컬/배포된주소 환경변수로 추가

src/main/java/com/supernova/fashionnova/domain/cart/Cart.java, src/main/java/com/supernova/fashionnova/domain/cart/CartController.java, src/main/java/com/supernova/fashionnova/domain/cart/CartService.java, src/main/java/com/supernova/fashionnova/domain/review/ReviewController.java, src/main/java/com/supernova/fashionnova/domain/review/ReviewService.java
=> ♻️ REFACTOR: 필요없는 주석, 줄바꿈 제거
